name: zimeng44/studio-rat-bundle
services:
  studio-rat:
    platform: linux/amd64
    image: zimeng44/studio-rat-dev:latest
    # container_name: studio-rat
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    # Set envrionment variables based on the .env file
    env_file:
      - .env
    # Set environment variables directly in the docker-compose file
    environment:
      NODE_ENV: 'development'
      POSTGRES_ADDR: 'postgres'
      POSTGRES_DATABASE: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # - .:/app
      - studio-rat-data:/app/public/uploads
    restart: always
    ports:
      - 3000:3000
    # command: "sh -c 'cd studio-rat; npm install; npx prisma migrate deploy; npx prisma db seed'"
  postgres:
    platform: linux/amd64
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  pgdata: {}
  studio-rat-data: {}