import type { Metadata, ResolvingMetadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
// import { getGlobalPageData, getGlobalPageMetadata } from "@/data/loaders";
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";
import { describe } from "node:test";
import { unstable_noStore as noStore } from "next/cache";
import { Suspense } from "react";
import { NavigationEvents } from "@/components/custom/navigation-events";
import type { Viewport } from "next";
import { cn } from "@/lib/utils";
// import prisma from "@/lib/prisma";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Faclity Management",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  // noStore();
  // const metadata = await getGlobalPageMetadata();
  const metadata = {};

  return {
    title: "Studio Rat",
    description: "Your Studio Assistant",
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const globalData = await getGlobalPageData();
  const globalData = {
    id: 1,

    title: "Studio Rat",

    description: "Responsible for header and footer data",

    createdAt: "2024-07-13T02:53:05.191Z",

    updatedAt: "2024-08-12T06:39:08.905Z",

    publishedAt: "2024-07-13T02:53:06.268Z",

    header: {
      id: 1,

      ctaButton: {
        id: 3,

        url: "/signin",

        text: "Sign In",

        isExternal: false,
      },

      logoText: {
        id: 2,

        url: "/",

        text: "Studio Rat",

        isExternal: false,
      },
    },

    footer: {
      id: 1,

      text: "Made with love",

      socialLink: [
        {
          id: 5,

          url: "www.youtube.com",

          text: "YouTube",

          isExternal: true,
        },

        {
          id: 6,

          url: "www.github.com",

          text: "GitHub",

          isExternal: true,
        },

        {
          id: 7,

          url: "www.twitter.com",

          text: "Twitter",

          isExternal: true,
        },
      ],

      logoText: {
        id: 4,

        url: "/",

        text: "Summarize AI",

        isExternal: false,
      },
    },

    meta: {},
  };
  // console.log("here");
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex h-screen flex-col")}>
        <Toaster position="top-center" />
        <Header data={globalData.header} />
        <div className="grow">
          {children}
          <Suspense fallback={null}>
            <NavigationEvents />
          </Suspense>
        </div>
        {/* <Footer data={globalData.footer} /> */}
      </body>
    </html>
  );
}
