import type { Metadata, ResolvingMetadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

import { getGlobalPageData, getGlobalPageMetadata } from "@/data/loaders";
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";
import { describe } from "node:test";
import { unstable_noStore as noStore } from "next/cache";
import { Suspense } from "react";
import { NavigationEvents } from "@/components/custom/navigation-events";
import type { Viewport } from "next";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Faclity Management",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  // noStore();
  const metadata = await getGlobalPageMetadata();

  return {
    title: metadata?.title,
    description: metadata?.description,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalPageData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" />
        <Header data={globalData.header} />
        <div>
          {children}{" "}
          <Suspense fallback={null}>
            <NavigationEvents />
          </Suspense>
        </div>
        {/* <Footer data={globalData.footer} /> */}
      </body>
    </html>
  );
}
